version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: crm_ticketing_db
    environment:
      POSTGRES_DB: crm_ticketing
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: crm_ticketing_api
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: "postgresql://postgres:password@postgres:5432/crm_ticketing?schema=public"
      PORT: 3001
      NODE_ENV: production
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      sh -c "
        npx prisma generate &&
        npx prisma db push &&
        npm start
      "

volumes:
  postgres_data:
